version: '3.8'
services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:delegated
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
    command: ['postgres', '-c', 'log_statement=all']

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5



  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${API_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      s3rver:
        condition: service_healthy


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - backend

  s3rver:
    image: node:18-alpine
    ports:
      - "${S3_PORT}:4569"
    volumes:
      - ./local-storage:/data
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install -g s3rver &&
             mkdir -p /data &&
             s3rver --address 0.0.0.0 --port 4569 --directory /data --configure-bucket auction"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:4569" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data:
  redis_data:


