#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running ESLint before push..."
npm run lint-app
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "Linting failed. Fix errors before pushing."
  exit 1
fi

